name: campus_cravings
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  auto_route: ^9.2.2
  another_flushbar: ^1.12.30
  flutter_otp_text_field: ^1.2.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  otp_pin_field: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/jpg/
  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/SofiaPro/SofiaPro-Regular.otf
        - asset: assets/fonts/SofiaPro/SofiaPro-Thin.otf
          weight: 100
        - asset: assets/fonts/SofiaPro/SofiaPro-UltraLight.otf
          weight: 200
        - asset: assets/fonts/SofiaPro/SofiaPro-Light.otf
          weight: 300
        - asset: assets/fonts/SofiaPro/SofiaPro-Medium.otf
          weight: 500
        - asset: assets/fonts/SofiaPro/SofiaPro-Bold.otf
          weight: 700
        - asset: assets/fonts/SofiaPro/SofiaPro-UltraBold.otf
          weight: 800
        - asset: assets/fonts/SofiaPro/SofiaPro-Black.otf
          weight: 900
